#!/bin/env bash

REMOTE_NAME="Onedrive:/backup"

# Exit if not inside a Git repo
git rev-parse --is-inside-work-tree >/dev/null 2>&1 || {
    exit 0
}

REPO_ROOT=$(git rev-parse --show-toplevel)
RELATIVE_PATH="${REPO_ROOT#"$HOME/"}"

echo "[AUTO-SYNC] $REMOTE_NAME/$RELATIVE_PATH -> $REPO_ROOT"

rclone copy "$REMOTE_NAME/$RELATIVE_PATH" "$REPO_ROOT" --update
