#!/bin/env bash

REMOTE_NAME="Onedrive:/backup"

# Exit if not inside a Git repo
git rev-parse --is-inside-work-tree >/dev/null 2>&1 || {
    exit 0
}

REPO_ROOT=$(git rev-parse --show-toplevel)
RELATIVE_PATH="${REPO_ROOT#"$HOME/"}"

IGNORED_FILES=$(git ls-files -i -o --exclude-standard | grep -v "^node_modules/" | grep -v "^dist/" | grep -v "^build/" | grep -v "^target/" | grep -v "^venv" | grep -v "^vcpkg_installed")
if [ -z "$IGNORED_FILES" ]; then
    echo "No ignored directories found — nothing to sync."
    exit 0
fi
echo "[AUTO-SYNC] $REPO_ROOT → $REMOTE_NAME/$RELATIVE_PATH"

echo "$IGNORED_FILES" | \
rclone copy "$REPO_ROOT" "$REMOTE_NAME/$RELATIVE_PATH" --files-from -
